http:
  port: 3000
admin:
  port: 9876
  hostname: localhost
apiEndpoints:
  service:
    host: localhost
    paths: ['/service','/service/*']
serviceEndpoints:
  wiremock:
    url: 'http://localhost:9999'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
  - rewrite
pipelines:
  default:
    apiEndpoints:
      - service
    policies:
      - rewrite:
          - condition:
              name: regexpmatch
              match: ^/service/(.*)$
            action:
              rewrite: /service100/$1
      - proxy:
          - action:
              serviceEndpoint: wiremock 
              changeOrigin: true

